### ISSUE TITLE
Create countries map on compile time

### ISSUE THREAD

**Issue by h4cc** [SebastianSzturo/countries#2]
As far as i can see, any call to this library will result in parsing YAML files.

How about creating that lookup table and data on compile time, instead on runtime? That would speed up any call to this library an eliminate any disk access.

Maybe have a look at some code i used to generate functions bodies while compiling here:
https://github.com/h4cc/slugger/blob/master/lib/slugger.ex#L69

**Comment by SebastianSzturo** [comment]
Thanks for the advice!
I tried to follow your tipp and load the yaml files on compile time, but it seams like its not possible to use ```:yamerl``` before the file is fully compiled.

```Elixir
== Compilation error on file lib/countries.ex ==
** (MatchError) no match of right hand side value: :undefined
    src/yamerl_app.erl:66: :yamerl_app.get_param/1
    src/yamerl_constr.erl:449: :yamerl_constr.setup_node_mods/1
    src/yamerl_constr.erl:519: :yamerl_constr.initialize/1
    src/yamerl_constr.erl:227: :yamerl_constr.file/2
```
I will try to cache the data, so it won't get read from disk every time.

**Comment by SebastianSzturo** [comment]
Nvm, I have to ensure that :yamerl is running with ``Application.ensure_all_started(:yamerl)``. 
The applications defined in the mix file get started after our application is compiled.

**Comment by h4cc** [comment]
:+1:
