### ISSUE TITLE
Subdivisions not loaded when app is built in different directory than it's run from

### ISSUE THREAD

**Issue by monorkin** [SebastianSzturo/countries#31]
Hi!

I've encountered an issue with this package while using it in an app running on Heroku.
While countries are loaded fine, and can be retrieved without issue, the same doesn't hold true for subdivisions.

## Cause
I've managed to track this issue all the way to the `__DIR__` in [subdivisions.ex](https://github.com/SebastianSzturo/countries/blob/master/lib/subdivisions.ex#L42) which got (somehow) expanded during compile time to `/tmp/...`. 

This is visible if you open the `Elixir.Counties.Subdivisions.beam` file on the instance. Since the Heroku Elixir buildpack runs the app from `/app`, but Heroku builds/compiles the app in `/tmp` this leaves an incorrect path in the compiled `.beam` file and when run the application can't locate the correct `yaml` file and fall-back to `[]`.

Countries work because they are loaded at compile-time, in contrast to subdivisions which are loaded dynamically. And rightly so, as loading all subdivisions into memory would be quite a large overhead.

## Workaround 
I've found two temporary workarounds for this issue.
1. Connect to an running instance using `heroku ps:exec` and run `mix deps.compile countries --force`
2. Find the build path, or use `$BUILD_PATH` if set, run `heroku ps:exec` and then `ln -s $BUILD_PATH /app/deps`

Both workarounds are temporary as you can't be sure when will Heroku spin up a new Dyno for your application, and the workaround doesn't survive redeploys.

## Solution
I'm not aware of any way to solve this. This is an attempt to make the issue visible to others.
My instinct tells me that, perhaps, it would be better to store data in the `priv` direcotry and use erlang's `:code.priv_dir(Countires)` or Elixir's `Application.app_dir(:countires, "priv/countires")` to access the data.

## Reproduction
1. Spin up a Heroku instance with any Phoenix application on Elixir `1.6.5` and erlang `20.1` using `countries`.
2. Run `iex -S mix`
3. Enter `Countries.filter_by(:alpha2, "US") |> List.first() |> Countries.Subdivisions.all()`

It returns an empty List

## Expected
1. Spin up a Heroku instance with any Phoenix application using `countries`.
2. Run `iex -S mix`
3. Enter `Countries.filter_by(:alpha2, "US") |> List.first() |> Countries.Subdivisions.all()`

It returns an *non* empty List

## Configuration
Elixir 1.6.5
Erlang 20.1

**Comment by stocks29** [comment]
Here is a PR which fixes this: https://github.com/SebastianSzturo/countries/pull/38
