### ISSUE TITLE
Cut a release from Master

### ISSUE THREAD

**Issue by zacksiri** [SebastianSzturo/countries#41]
Hey I ran into a problem where the Subdivisions data was not being loaded.

I also saw that the data has been moved into the priv directory which solve the problem where the data is missing from release. However the latest version `1.5.1` is not a reflection of what is in the master branch.

Any chance we can get an updated version in hex?

**Comment by steffenix** [comment]
@SebastianSzturo

**Comment by SebastianSzturo** [comment]
I released a new `1.6.0` version from master 👍
