### ISSUE TITLE
Project still maintained?

### ISSUE THREAD

**Issue by dnlserrano** [SebastianSzturo/countries#49]
Hey @SebastianSzturo @steffenix thanks so much for your work on this library.

Is it still maintained? Do you have plans to merge open PRs and take care of outstanding issues? Can we, as a community, help you out?

Thanks again for you work for the Elixir community. I look forward to be able to contribute.

\- Daniel ❤️

**Comment by steffenix** [comment]
PR merged.

**Comment by dnlserrano** [comment]
Thank you. Any plans for a new release?

**Comment by steffenix** [comment]
@SebastianSzturo you want to transfer the ownership to me? I will take care of the lib and hex.pm
