### ISSUE TITLE
Update Hex.pm

### ISSUE THREAD

**Issue by syamilmj** [SebastianSzturo/countries#9]
Hey, thanks for the great work! :)

Would you mind updating the package on Hex.pm? Some issues that was already fixed like #5 is still there.

Thanks!

**Comment by JoshSmith** [comment]
@SebastianSzturo any chance of an updated release to hex (and maybe a badge in here)?

**Comment by SebastianSzturo** [comment]
Sorry for the late reply! I updated the yamerl dependency and pushed a new version (1.2.0) to hex. Can you confirm that everything is working, so we can update the README?

**Comment by JoshSmith** [comment]
@SebastianSzturo no worries! It all seems fine to me and I've added #10 for us to update the README.
